### PR TITLE
Add simple vorpal example

### PR DESCRIPTION
**Pull request by OR13**
If this looks good, I can proceed to replicate all existing shell commands. vorpal can help enforce required arguments, but the existing shell seemed to use optional arguments as required. I defaulted them to make them optional, but they could also be made required, and no additional error handling logic would be needed.

https://github.com/dthree/vorpal/wiki/api-%7C-vorpal.command#vorpalcommandcommand-description

Since this tool is initially for testing, I recommend not making arguments required and picking reasonable defaults so the flow can be quickly run through, like so:

```
› npm run truebit

> truebit-client@1.0.0 truebit /Users/orie/Desktop/tech-spikes/truebit-os
> node ./cli/index.js basic-client/config.json

  _____                         _       _   _       
 |_   _|  _ __   _   _    ___  | |__   (_) | |_   _ 
   | |   | '__| | | | |  / _ \ | '_ \  | | | __| (_)
   | |   | |    | |_| | |  __/ | |_) | | | | |_   _ 
   |_|   |_|     \__,_|  \___| |_.__/  |_|  \__| (_)
                                                    
  _            _                _                            _  __       
 | |_ __ _ ___| | __  ___  ___ | |_   _____  __   _____ _ __(_)/ _|_   _ 
 | __/ _` / __| |/ / / __|/ _ \| \ \ / / _ \ \ \ / / _ \ '__| | |_| | | |
 | || (_| \__ \   <  \__ \ (_) | |\ V /  __/  \ V /  __/ |  | |  _| |_| |
  \__\__,_|___/_|\_\ |___/\___/|_| \_/ \___|   \_/ \___|_|  |_|_|  \__, |
                                                                   |___/ 
🎲   $ 2018-06-04 22:05:21 [console] info: Truebit OS has been initialized with config at basic-client/config.json
🎲   $ start task
2018-06-04 22:05:26 [console] info: Task Giver initialized
🎲   $ start solve
2018-06-04 22:05:29 [console] info: Solver initialized
🎲   $ task
🎲   $ 2018-06-04 22:05:34 [console] info: Task submitted 0xbfdf4d4185cf59347a6014a6054b83767a901d14fd6b70e4ebbbeaec6bfbbe75
🎲   $ skip
🎲   $ Error: VM Exception while processing transaction: revert
```

### CODE REVIEW

**Comment by OR13** [comment]
I recommend not reusing words for commands / agents, such as task. For example:

```
start task-submitter -a 0
submit-task -a 0 -t testTask.json
```

**Comment by hswick** [comment]
The vorpal stuff seems very reasonable.

In terms of commands, I agree that the task stuff seems confusing. I think we should do this:
```
start task -a 0
submit-task -a 0 -t testTask.json
```

**Comment by OR13** [comment]
Cool, I will continue, and use that approach.

**Comment by OR13** [comment]
Leaving this here for reference: https://github.com/dthree/cash/tree/master/test

Testing CLI's is difficult. The functions can be tested, on the full tool can be tested.

I think the best approach is to have vorpal call a library function, and then write tests for each of those functions. This saves you from needing to handle stdout/stderr.

**Comment by hswick** [comment]
Testing stdout would be fancy, but probably not necessary for the time. The functions that the cli's should be calling are mostly in the tests now, so I think that will be sufficient.

In terms of the UI, manually going through to check isn't too bad since there aren't too many commands at the moment.

**Comment by OR13** [comment]
I've taken some stylist liberties here, happy to remove them (the dice). Just want to show what can be done.

**Comment by OR13** [comment]
travis is so picky... this passed on my side. https://travis-ci.org/OR13/truebit-os/builds/389775141

I need to add the tests that I have written and test again.

**Comment by OR13** [comment]
Objective here is to get the cliLib tests to pass along side the os tests. I'm seeing some revert failure when running os-challenge.

This is caused by the addition of the verifier. The `os-challenge` test does not actually test the verifier, and its presence causes failure.

I'm happy to tackle fixing that test in a separate pr.

**Comment by OR13** [comment]
If we are happy with travis tests passing in this form: 

https://travis-ci.org/TrueBitFoundation/truebit-os/builds/390175190#L914

I suggest we merge this PR, and I can tackle the verifier (os-challenge) bit next.

I can also remove reference to the old shell and cleanup a bit, but I don't want to do that unless its requested.

**Comment by hswick** [comment]
Great work! Yes please remove any references of old shell, we have no use for it anymore.

**Comment by OR13** [comment]
Now we know why the builds were failing... If i had a penny for every-time truffle / testrpc / ganache / web3 version slipped and broke my stuff... I'd have lots of pennies....

https://travis-ci.org/TrueBitFoundation/truebit-os/jobs/391048018#L461

**Comment by OR13** [comment]
I'd say this is safe to merge now.

**Comment by hswick** [comment]
Looks good! Really appreciate the effort on this!

**Pull request merged**
